
development:
  adapter: postgresql
  database:
  pool: 5
  timeout: 5000
  username: Core


test:
  adapter: postgresql
  database:
  pool: 5
  timeout: 5000
  username: Core

production:
  adapter: postgresql
  database:
  pool: 5
  timeout: 5000
  username: Core
